[package]
name = "rhai_rustler"
version = "0.1.0"
authors = ["Fabrizio Sestito <fabrizio.sestito@suse.com>"]
edition = "2018"

[lib]
name = "rhai_rustler"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
rhai = "1.10.1"
